import StatCard from '../StatCard/StatCard';
import './Stats.css';

function Stats() {
    return(
        <div className="stats-container container">
            <p className="stats-title">Better machine <span>performance</span> for better maintenance teams' <span>productivity</span></p>
            <div className="stats-cards-container">
                <StatCard perc="20%" desc="ASSERTIVENESS OF INSIGHTS GENERATED BY TRACTIAN PLATFORM" />
                <StatCard perc="45%" desc="INCREASED RELIABILITY OF MACHINES WITH TRACTIAN SOLUTION." />
                <StatCard perc="30%" desc="REDUCTION OF LAST-MINUTE MAINTENANCE OCCURRENCES." />
            </div>
        </div>
    )
}

export default Stats;